apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: {{ .Release.Namespace }}
  {{- with .Values.kubevirt.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.kubevirt.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.kubevirt.configuration }}
  configuration:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.kubevirt.customizeComponents }}
  customizeComponents:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  imagePullPolicy: {{ .Values.kubevirt.imagePullPolicy }}
  {{- with .Values.kubevirt.infra }}
  infra:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.kubevirt.uninstallStrategy }}
  uninstallStrategy: {{ .Values.kubevirt.uninstallStrategy }}
  {{- end }}
  {{- with .Values.kubevirt.workloads }}
  workloads:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.kubevirt.workloadUpdateStrategy }}
  workloadUpdateStrategy:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.kubevirt.monitorNamespace }}
  monitorNamespace: {{ .Values.kubevirt.monitorNamespace }}
  {{- end }}
  {{- if .Values.kubevirt.monitorAccount }}
  monitorAccount: {{ .Values.kubevirt.monitorAccount }}
  {{- end }}
