apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: {{ .Release.Namespace }}
  {{- with .Values.kubevirt.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.kubevirt.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ include "kubevirt.spec" . | nindent 2 }}
