annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Rancher Turtles - the Cluster API Extension
  catalog.cattle.io/kube-version: '>= 1.23.0-0'
  catalog.cattle.io/namespace: rancher-turtles-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/rancher-version: '>= 2.9.0-1'
  catalog.cattle.io/release-name: rancher-turtles
  catalog.cattle.io/scope: management
  catalog.cattle.io/type: cluster-tool
apiVersion: v2
appVersion: 0.13.0
dependencies:
- condition: cluster-api-operator.enabled
  name: cluster-api-operator
  repository: file://./charts/cluster-api-operator
  version: 0.14.0
description: Rancher Turtles is an extension to Rancher that brings full Cluster API
  integration to Rancher.
home: https://github.com/rancher/turtles/
icon: https://raw.githubusercontent.com/rancher/turtles/main/logos/capi.svg
keywords:
- rancher
- cluster-api
- capi
- provisioning
name: rancher-turtles
type: application
version: 0.4.0+up0.13.0
