apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-bmo
  labels:
    {{- include "ironic.labels" . | nindent 4 }}
data:
  {{- $protocol := "http" }}
  {{- $ironicApiHost := .Values.global.ironicApiHost }}
  {{- $ironicBootHost := .Values.global.ironicBootHost }}
  {{- $ironicInspectorHost := .Values.global.ironicInspectorHost }}
  {{- $ironicCacheHost := .Values.global.ironicCacheHost }}

  {{- if .Values.global.ironicIP }}
  {{- $ironicApiHost = print .Values.global.ironicIP ":6385" }}
  {{- $ironicBootHost = print .Values.global.ironicIP ":6180" }}
  {{- $ironicInspectorHost = print .Values.global.ironicIP ":5050" }}
  {{- $ironicCacheHost = print .Values.global.ironicIP ":6180" }}
  {{- end }}

  {{- if  ( .Values.global.enable_tls ) }}
    {{- $protocol = "https" }}
  {{- end }}
  {{- if  ( .Values.global.enable_dnsmasq ) }}
  DNSMASQ_BOOT_SERVER_ADDRESS: {{ $ironicBootHost }}
  DNSMASQ_DNS_SERVER_ADDRESS: {{ tpl .dnsmasqDnsServerAddress $ }}
  DNSMASQ_DEFAULT_ROUTER: {{ .Values.global.dnsmasqDefaultRouter }}
  DHCP_RANGE: {{ .Values.global.dhcpRange }}
  {{- end }}
  {{- with .Values.baremetaloperator }}
  CACHEURL: {{ $protocol }}://{{ $ironicCacheHost }}/images
  DEPLOY_KERNEL_URL: {{ $protocol }}://{{ $ironicBootHost }}/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: {{ $protocol }}://{{ $ironicBootHost }}/images/ironic-python-agent.initramfs
  {{- if  .dhcpHosts }}
  DHCP_HOSTS: {{ .dhcpHosts }}
  {{- end }}
  HTTP_PORT: {{ .httpPort | quote }}
  {{- if .ipaBaseUri }}
  IPA_BASEURI: {{ .ipaBaseUri }}
  {{- end }}
  IRONIC_API_BASE_URL: {{ $protocol }}://{{ $ironicApiHost }}
  IRONIC_API_HOST: {{ $ironicApiHost }}
  IRONIC_API_HTTPD_SERVER_NAME: {{ $ironicApiHost }}
  IRONIC_BOOT_BASE_URL: {{ $protocol }}://{{ $ironicBootHost }}
  IRONIC_ENDPOINT: {{ $protocol }}://{{ $ironicApiHost }}/v1/
  IRONIC_INSPECTOR_BASE_URL: {{ $protocol }}://{{ $ironicInspectorHost }}
  IRONIC_INSPECTOR_ENDPOINT: {{ $protocol }}://{{ $ironicInspectorHost }}/v1/
  IRONIC_INSPECTOR_HOST: {{ $ironicInspectorHost }}
  IRONIC_INSPECTOR_HTTPD_SERVER_NAME: {{ $ironicInspectorHost }}
  IRONIC_RAMDISK_SSH_KEY: {{ .ironicRamdiskSshKey }}
  IRONIC_VMEDIA_HTTPD_SERVER_NAME: {{ $ironicBootHost }}
  {{- end }}
  ENABLE_PXE_BOOT: "{{ .Values.global.enable_pxe_boot }}"
  {{- if .Values.global.provisioningInterface }}
  PROVISIONING_INTERFACE: {{ .Values.global.provisioningInterface }}
  {{- end }}
  {{- if .Values.global.provisioningIP }}
  PROVISIONING_IP: {{ .Values.global.provisioningIP }}
  {{- end }}
  IRONIC_INSPECTOR_VLAN_INTERFACES: all
  IRONIC_ILO_USE_SWIFT: "false"
  IRONIC_ILO_USE_WEB_SERVER_FOR_IMAGES: "true"
  IRONIC_FAST_TRACK: "true"
  IRONIC_REVERSE_PROXY_SETUP: "false"
  IRONIC_USE_MARIADB: "true"
  LISTEN_ALL_INTERFACES: "true"
  {{- if  ( .Values.global.enable_tls ) }}
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "true"
  IRONIC_KERNEL_PARAMS: console=ttyS0 suse.cafile={{ $protocol }}://{{ $ironicBootHost }}/tstcerts/ca.crt
  IPA_INSECURE: "0"
  {{- else }}
  RESTART_CONTAINER_CERTIFICATE_UPDATED: "false"
  IRONIC_KERNEL_PARAMS: console=ttyS0
  IPA_INSECURE: "1"
  {{- end }}
  DATABASE_HOST: {{ .Values.global.databaseServiceName }}.{{ .Release.Namespace }}.svc.cluster.local