apiVersion: v2
appVersion: v0.14.3
dependencies:
- condition: frrk8s.enabled
  name: frr-k8s
  repository: file://./charts/frr-k8s
  version: 0.0.15
- condition: crds.enabled
  name: metallb-crds
  repository: file://./charts/metallb-crds
  version: 0.14.8
description: A network load-balancer implementation for Kubernetes using standard
  routing protocols
home: https://metallb.universe.tf
icon: https://metallb.universe.tf/images/logo/metallb-white.png
kubeVersion: '>= 1.19.0-0'
name: metallb
sources:
- https://github.com/metallb/metallb
type: application
version: 0.14.9
