---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: capm3-system/capm3-serving-cert
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: capm3-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capm3-webhook-service
      namespace: capm3-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-metal3cluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.metal3cluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metal3clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capm3-webhook-service
      namespace: capm3-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-metal3data
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.metal3data.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metal3datas
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capm3-webhook-service
      namespace: capm3-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-metal3dataclaim
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.metal3dataclaim.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metal3dataclaims
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capm3-webhook-service
      namespace: capm3-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-metal3datatemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.metal3datatemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metal3datatemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capm3-webhook-service
      namespace: capm3-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-metal3machine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.metal3machine.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metal3machines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capm3-webhook-service
      namespace: capm3-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-metal3machinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.metal3machinetemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metal3machinetemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capm3-webhook-service
      namespace: capm3-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-metal3remediation
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.metal3remediation.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metal3remediations
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capm3-webhook-service
      namespace: capm3-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-metal3remediationtemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.metal3remediationtemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metal3remediationtemplates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: capm3-system/ipam-serving-cert
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: ipam-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ipam-webhook-service
      namespace: capm3-system
      path: /validate-ipam-metal3-io-v1alpha1-ipaddress
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.ipaddress.ipam.metal3.io
  rules:
  - apiGroups:
    - ipam.metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ipaddresses
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ipam-webhook-service
      namespace: capm3-system
      path: /validate-ipam-metal3-io-v1alpha1-ipclaim
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.ipclaim.ipam.metal3.io
  rules:
  - apiGroups:
    - ipam.metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ipclaims
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ipam-webhook-service
      namespace: capm3-system
      path: /validate-ipam-metal3-io-v1alpha1-ippool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.ippool.ipam.metal3.io
  rules:
  - apiGroups:
    - ipam.metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ippools
  sideEffects: None
