---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: capm3-selfsigned-issuer
  namespace: capm3-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: ipam-selfsigned-issuer
  namespace: capm3-system
spec:
  selfSigned: {}
