---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: capm3-webhook-service
  namespace: capm3-system
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    cluster.x-k8s.io/provider: infrastructure-metal3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: ipam-webhook-service
  namespace: capm3-system
spec:
  ports:
  - port: 443
    targetPort: ipam-webhook
  selector:
    cluster.x-k8s.io/provider: infrastructure-metal3
