---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: capm3-manager
  namespace: capm3-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: ipam-manager
  namespace: capm3-system
